### ISSUE TITLE
Adding parameter to start_url

### ISSUE THREAD

**Issue by boerni** [SayHelloGmbH/progressive-wordpress#19]
Hi,

i tried to add parameters to the start_url like "/?ref=app" to know where the request comes from.
But it is not possible with your regexp restrictions in the function starturl_sanitize.

Is it really necessary to restrict this?

Thanks!

**Comment by nico-martin** [comment]
Hi @boerni,
Good point. I will change this in the next version.
Kind regards,
Nico

**Comment by nico-martin** [comment]
fixed in Version 1.2.0
