### ISSUE TITLE
error upload icon

### ISSUE THREAD

**Issue by guslalo** [SayHelloGmbH/progressive-wordpress#21]
Hello my friend, upload icon does not work

error:
admin.js?ver=1.2.0:429 Uncaught TypeError: Cannot read property 'url' of undefined
    at e.Collection.<anonymous> (admin.js?ver=1.2.0:429)

if (attachment.type === 'image') {
						preview = '<img src=\'' + attachment.sizes.thumbnail.url + '\' />';
					} else {
						preview = '<a target="_blank" href="' + attachment.url + '">' + attachment.title + '</a> (' + attachment.mime + ')';
					}

**Comment by nico-martin** [comment]
Hi, are you still having the issue?

Kind regards,
Nico

**Comment by vineettalwar** [comment]
Hi Nico, 
I can confirm the issue, icon upload feature is not working with certain dimensions. When I uploaded bigger icon, 512x512 it worked.
Suggestion: If it works with certain icon dimensions. This should be mention somewhere in instructions at the upload field  :)
