### ISSUE TITLE
How to track users

### ISSUE THREAD

**Issue by aleksandrguru** [SayHelloGmbH/progressive-wordpress#32]
I do not understand yet another thing about how to track users, not only with Google analytics, how to use other systems

**Comment by nico-martin** [comment]
You can track users by adding custom parameters to the start url. So each time a user opens the PWA it opens the start url. And if you add some parameters to it you can work with them.

There is a filter `web_app_manifest` where you can override the manifest values, therefore add parameters to the start URL. Here ist the example how I'm doing it for google analytics:

calling the filter:
https://github.com/SayHelloGmbH/progressive-wordpress/blob/master/Classes/class-tracking.php#L29

changing the values:
https://github.com/SayHelloGmbH/progressive-wordpress/blob/master/Classes/class-tracking.php#L93

little example:
```php
add_filter( 'web_app_manifest', function( $values ) {
  $values['start_url'] = $values['start_url'] . '?myparam=custom';
  return $values;
}, 500 );
```
