### ISSUE TITLE
Table has no rows.× pwa-directory.appspot.com

### ISSUE THREAD

**Issue by aleksandrguru** [SayHelloGmbH/progressive-wordpress#33]
If you add an application to it it shows the following errors
https://pwa-directory.appspot.com

LIGHTHOUSE
Table has no rows.×
WebPageTest
Data must contain at least two columns.
PageSpeed Insights
Data must contain at least two columns.

**Comment by nico-martin** [comment]
I don't know https://pwa-directory.appspot.com and I have also no idea that those errors mean. Sorry. but your PWA works, right?
