### ISSUE TITLE
Remove plugin admin CSS from public pages 

### ISSUE THREAD

**Issue by earcos** [SayHelloGmbH/progressive-wordpress#38]
The plugin admin CSS is being added to public pages for no reason.

**Comment by etalented** [comment]
@nico-martin can you feedback on this?

**Comment by nico-martin** [comment]
Hi @earcos 

Thank you, I just published anew version where I created multipbe JS/CSS files for the frontend and now I load them conditionaly depending on the features you want to use in the frontend.

Kind regards,
Nico
