### ISSUE TITLE
Does it support iOS

### ISSUE THREAD

**Issue by chunting80** [SayHelloGmbH/progressive-wordpress#39]
Hi there,

Managed to install for android but didn’t see it working for iOS?
Does it support. Appreciate ig

**Comment by etalented** [comment]
@nico-martin can you feedback on this?

**Comment by nico-martin** [comment]
Hi @chunting80 

Yes it works for iOS as far iOS supports progressive web apps.
For the add to homescreen functionality for example there is no install prompt, but you can install as its explained here:


![iOS a2h](https://nicomartin.ch/ios-install-pwa.jpg)
