### ISSUE TITLE
Do not cache wp-json requests

### ISSUE THREAD

**Issue by pascalknecht** [SayHelloGmbH/progressive-wordpress#40]
Requests to the WordPress API /wp-json should not be cached as they break gutenberg.
Hence the following addition to the pwp-serviceworker.js on line 2 should be made:
`|| request.url.match(/wp-json/) { return }`

**Comment by nico-martin** [comment]
Hi @pascalknecht, instead of changing the serviceworker directly I added a new "network first" caching strategy for wp-json requests (same as for wp-admin requests)
