### ISSUE TITLE
"Add to home screen" button is not appearing anymore

### ISSUE THREAD

**Issue by Harry-VV** [SayHelloGmbH/progressive-wordpress#56]
Hi Nico,

First of all, thanks a lot; your Progressive WordPress (PWA) is simply the best! 
I tried all PWA plugins but your plugin is THE plugin.

Today I tried to install the app again and discovered that the 'Add to homescreen' button did not appear anymore... and I can't discover why. 

- My site/ shop is https
- I tried it mobile on Chrome 80.0.3987.132
- Android 7,0
- All plugins (Woocommerce, ...) are up to date

The settings:
Show "add to homescreen" banner        - Normal
Default caching strategy	 	                - Stale
Caching strategy for CSS and JS Files	- Stale
Caching strategy for images		        - Network
Caching strategy for fonts		        - Network
Caching strategy for WP Rest		        - Network

Hope you have the golden tip for me.

Thanks,
Harry

**Comment by nico-martin** [comment]
Hi @Harry-VV 

At the end its the browser that decides if and when it shows the prompt. For example if you dismissed it before, it won’t be shown again.
To be sure you should go to Chrome Settings -> Settings -> Website settings -> storage -> search for your site and delete all data.
That way you could visit your website like a first time visitor.
Or you could go to chrome settings -> add to homescreen. That way your PWA will be added to your homescreen directly.

A more reliable way would be to configure a own Add to homescreen button using the "Show 'add to homescreen' banner" = "on element click"
